site_name: chizhiga Docs
site_description: the notes record by chizhiga
site_author: chizhiga #作者名
site_url: https://chizhiga.github.io/  #网站地址
copyright: Copyright &copy; 2023 chizhiga # 左下角的版权声明
repo_url: https://github.com/CHIZHIGA/chizhiga.github.io # 右上角点击跳转的链接
repo_name: FZU-chizhiga



nav:
  - Home: about/index.md
  - Java学习:  
    - JavaWeb: mk/JavaWeb.md
    - MySQL: mk/MySQL.md
  - Demo: 
    - 福州大学教务处: mk/05.福大教务处-正文.html
  - 控制:
    - 先导课:
      - Research Proposal: control/pre/29.md
    - FZU:
      - Proportional controller design for a feedback system: control/fz/ass1.md
  
  


theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.path #
    - navigation.top #
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon: # 'clound' 右上角图标的另一种样式，需要注释下行
    repo: fontawesome/brands/github


